# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endere\xe7o')),
                ('numero', models.CharField(max_length=11, verbose_name='N\xfamero')),
                ('estado', models.CharField(max_length=1, verbose_name='Estado')),
                ('tipo', models.CharField(max_length=1, verbose_name='Tipo de Us\xfaario')),
                ('celular', models.CharField(max_length=30, verbose_name='N\xfamero do Celular')),
                ('cep', models.CharField(max_length=8, verbose_name='Cep')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('usuario', models.CharField(max_length=50, verbose_name='Usu\xe1rio')),
                ('senha', models.CharField(max_length=50, verbose_name='Senha')),
                ('confirmarsenha', models.CharField(max_length=50, verbose_name='Confirmar Senha')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo')),
                ('foto', models.ImageField(blank=True, default='cliente/no_foto.jpg', null=True, upload_to='cliente/')),
            ],
            managers=[
                ('cliente', django.db.models.manager.Manager()),
            ],
        ),
    ]
